### PR TITLE
Adding Bellbot to strands apps

### PR DESCRIPTION
**Pull request by Jailander**
moving PR #30 here fixing compilation bugs

### CODE REVIEW

**Comment by marc-hanheide** [comment]
Sorry, I lost track a little bit... so also the bellbot_gui should go here? isn't it AAF specific?

**Comment by cdondrup** [comment]
Actually @Jailander and I talked a bit about this yesterday. From what I understand the gui is not specific and could also be used at G4S or anywhere else. I didn't quite agree with splitting the GUI from the scheduler then because they are very intertwined but that was the groups decision and they will have had their reasons. 
Nevertheless, I don't think any of this should go into `strands_apps` but rather into `strands_hri` because it is mainly human robot interaction and not a generic app. I don't want `strands_apps` to become the new `strands_utils` ;)

**Comment by Jailander** [comment]
yes @cdondrup that is exactly my fear, I will take a deeper look and try to reduce the packages to two and put them in the right place

**Comment by cdondrup** [comment]
Putting all of this here would also mean that `strands_apps` depends on the scheduler, the navigation, people perception, etc. This is less than appropriate and it should really be the other way around. I therefore strongly argue to not put this here because so far `strands_apps` only contains low-level applications.

**Comment by Jailander** [comment]
yes looking at https://lcas.lincoln.ac.uk/jenkins/job/generate_report/lastSuccessfulBuild/artifact/repos.png I think 'strands_apps' its basically the worst place for this, 'strands_hri' seems a bit unrelated, I think 'strands_deployment' would be ideal if we consider this to be general deployment applications however it looks like the new 'strands_util'

**Comment by Jailander** [comment]
taking a closer look with @cdondrup  'strands_hri' is the best place for it, shall I move it there @marc-hanheide @yianni ?

**Comment by marc-hanheide** [comment]
Yes, as usual I agree ;-)

**Pull request closed without merging**
