### PR TITLE
adding wait to the door passing action

### PR DESCRIPTION
**Pull request by bfalacerda**
This tackles https://github.com/strands-project/g4s_deployment/issues/84

It introduces a new action server `door_wait_and_pass` that waits for a predefined amount of time in front of a door when it is closed. If the door is open for more than 2 seconds, the robot speaks, saying he will go through and asking the person to keep holding the door.

The waiting time is defined via the param server, see https://github.com/bfalacerda/strands_apps/blob/indigo-devel/door_pass/scripts/door_wait_and_pass.py#L19

It also adds a stand-alone waiting node, to be used with the extended version of policy execution that is currently being developed for the TSC deployment. This has been tested for both the current and extended versions of policy execution.

Regardless, the only thing that needs to be done to use this is setting `door_wait_and_pass` instead of `doorPassing` as the nav action server between door edges in the topological map.

### CODE REVIEW

**Comment by hawesie** [comment]
An excellent start, thanks. We're going to need to test this pretty thoroughly somehow, with non-experts. Any thoughts on that?

**Comment by bfalacerda** [comment]
the UG floor has those fire doors, we can add some tasks that require going through them?

**Comment by hawesie** [comment]
That's what I was thinking too, but I'm quite nervous about someone also letting the robot through to the top of the **STAIRS**.

**Comment by bfalacerda** [comment]
that's why we have 2 of them?

Seriously, that would require the robot wanting to go to the wrong place and someone be willing to hold a door for him, I think it's quite safe. We can also add security with the magnetic strip and a forbidden topo node in that area.

**Comment by hawesie** [comment]
It’s my job to be nervous about these things!

**Comment by kunzel** [comment]
testing on LG? Falling up the stairs might be OK ;)

**Comment by hawesie** [comment]
> On 29 Mar 2016, at 10:13, Lars Kunze notifications@github.com wrote:
> 
> testing on LG? Falling up the stairs might be OK ;)

Sometimes I feel pretty dumb,

**Comment by bfalacerda** [comment]
I was thinking about UG because of the Sloman lounge, it's one of the most interesting places in the building for the robot. Also, the use of the doors in UG is more interesting because the robot can access the area behind them in 2 different ways.

Anyway, it's not that big of a deal, we can do it downstairs and use the lab doors for testing also.

**Comment by hawesie** [comment]
> On 29 Mar 2016, at 11:31, Bruno Lacerda notifications@github.com wrote:
> 
> Also, the use of the doors in UG is more interesting because the robot can access the area behind them in 2 different ways.

I didn’t know that. Ultimately it’s your call Bruno.

**Comment by bfalacerda** [comment]
I'm testing in LG. @hawesie are the doors in TSC double doors, and people only open one side to go through, or is it a single door?

**Comment by hawesie** [comment]
It's a single door. Here are some photos. Both doors open inwards to the short corridor. 

image

image

**Pull request merged**
